# Generated by Django 5.1.4 on 2025-02-06 22:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('turno', models.IntegerField(blank=True, choices=[(1, '1er Turno'), (2, '2do Turno'), (3, '3er Turno'), (4, '4to Turno')], null=True)),
                ('numero_reloj', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Jr', 'Ingeniero Jr'), ('Sr', 'Ingeniero')], default='Jr', max_length=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DOE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fase_actual', models.CharField(choices=[('infrastructure_and_material', 'Infrastructure and Material'), ('data_mining', 'Data Mining'), ('analysis', 'Analysis'), ('result_final', 'Result Final')], default='infrastructure_and_material', max_length=50)),
                ('archivo_te', models.FileField(blank=True, null=True, upload_to='archivos_te/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('data_mining_completed', models.BooleanField(default=False)),
                ('infrastructure_completed', models.BooleanField(default=False)),
                ('execution_completed', models.BooleanField(default=False)),
                ('result_final_completed', models.BooleanField(default=False)),
                ('prioridad', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataMining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('excel_data', models.FileField(upload_to='data_mining/')),
                ('dr', models.TextField()),
                ('doe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_mining', to='app.doe')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.doe')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='app.doe')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('infrastructure_and_material', 'Infrastructure and Material'), ('data_mining', 'Data Mining'), ('analysis', 'Analysis'), ('result_final', 'Result Final')], max_length=100)),
                ('archivo', models.FileField(upload_to='archivos_fases/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doe')),
            ],
        ),
        migrations.CreateModel(
            name='DOE_Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fase', models.CharField(choices=[('infrastructure_and_material', 'Infrastructure and Material'), ('data_mining', 'Data Mining'), ('final_review', 'Final Review'), ('completed', 'Completed')], max_length=50)),
                ('estado', models.CharField(default='En progreso', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('doe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases_relacionadas', to='app.doe')),
            ],
        ),
        migrations.AddField(
            model_name='doe',
            name='fases',
            field=models.ManyToManyField(related_name='does', to='app.doe_fase'),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(related_name='equipos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doe',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.equipo'),
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('pic', models.IntegerField(choices=[(1, '1 PIC'), (2, '2 PIC'), (3, '3 PIC'), (4, '4 PIC'), (5, '5 PIC')])),
                ('status_per_pic', models.TextField()),
                ('executive_summary', models.TextField()),
                ('doe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='app.doe')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('infrastructure_and_material', 'Infrastructure and Material'), ('data_mining', 'Data Mining'), ('analysis', 'Analysis'), ('result_final', 'Result Final')], max_length=100)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('tiempo_transcurrido', models.DurationField(blank=True, null=True)),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doe')),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_material', models.CharField(choices=[('material', 'Material'), ('unidad', 'Unidad')], default='material', max_length=10)),
                ('material_name', models.CharField(blank=True, max_length=255, null=True)),
                ('material_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('material_pn', models.CharField(blank=True, max_length=255, null=True)),
                ('rack', models.CharField(blank=True, max_length=255, null=True)),
                ('test_list', models.TextField(blank=True, null=True)),
                ('bay', models.CharField(blank=True, max_length=255, null=True)),
                ('doe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='app.doe')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(blank=True, default='Desconocido', max_length=255, null=True)),
                ('material_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('material_pn', models.CharField(blank=True, max_length=255, null=True)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='app.infrastructurematerial')),
            ],
        ),
        migrations.CreateModel(
            name='ResultFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt_final', models.FileField(upload_to='result_final/')),
                ('brief_conclusion', models.TextField()),
                ('doe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_final', to='app.doe')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('rn_number', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('bay', models.CharField(blank=True, max_length=255, null=True)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='app.infrastructurematerial')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('doe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doe')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('doe', 'usuario')},
            },
        ),
    ]
