# Generated by Django 5.1.4 on 2025-01-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doe',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_doe/'),
        ),
        migrations.AlterField(
            model_name='doe',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
