# Generated by Django 5.1.4 on 2025-02-07 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_execution_executive_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app.execution')),
            ],
        ),
    ]
