# Generated by Django 5.1.4 on 2025-01-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doe_archivo_alter_doe_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doe',
            name='fase_actual',
            field=models.CharField(choices=[('data_mining', 'Data Mining'), ('infrastructure', 'Infrastructure and Material'), ('execution', 'Execution'), ('result_final', 'Result Final')], default='data_mining', max_length=20),
        ),
    ]
