# Generated by Django 5.1.4 on 2025-02-07 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_executionlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='executive_summaries/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='app.execution')),
            ],
        ),
    ]
