# Generated by Django 5.1.4 on 2025-02-07 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_executivesummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultfinal',
            name='brief_conclusion',
        ),
        migrations.RemoveField(
            model_name='resultfinal',
            name='ppt_final',
        ),
        migrations.AddField(
            model_name='resultfinal',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PPTFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ppt_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppt_files', to='app.doe')),
            ],
        ),
    ]
