# Generated by Django 5.1.4 on 2025-02-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_resultfinal_brief_conclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doe',
            name='ejecucion_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doe',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
